### ISSUE TITLE
Make start_date and end_date work on the Historical Weather API page

### ISSUE THREAD

**Issue by sorentv2reg** [open-meteo/open-meteo-website#259]
Hi

I've extracted a lot of historical data and during testing it would be nice if you could link directly to the Historical Weather API page for a specific location and time. Example:

https://open-meteo.com/en/docs/historical-weather-api#latitude=57.048&longitude=9.9187&start_date=2023-06-09&end_date=2023-06-09&hourly=temperature_2m,apparent_temperature&timezone=Europe%2FBerlin

But for some reason the parameters start_date and end_date don't work (although they are injected into the URL when you use the date selector).

**Comment by sorentv2reg** [comment]
Not sure if this has been deployed but I noticed that it works if you copy/paste a URL directly into the address bar. But if you follow a link (like the above), it doesn't not work.

**Comment by patrick-zippenfenig** [comment]
Yes it is deployed and it is working for me. Could you force-reload the page? Maybe it is an cache issue (I do not have a sophisticated cache busting system yet....)
