### ISSUE TITLE
Broken links to Copernicus Climate Data Store

### ISSUE THREAD

**Issue by fuma900** [open-meteo/open-meteo-website#330]
All links to Copernicus new Climate/Common Data Store website appear to be broken.

Some of them seem easy to fix with the following find & replace:
`https://cds.climate.copernicus.eu/cdsapp#!/dataset` -> `https://cds.climate.copernicus.eu/datasets`
- `ERA5`
- `ERA5-Land`
- `ERA5-Ensemble`
- `CERRA`

I couldn't find the new link for the rest of them as I'm not 100% familiar with the old CDS website.

**Comment by patrick-zippenfenig** [comment]
Thanks for the report. I committed a fix with the new URLs.
